version: '3.6'
services:
  postgres:
    image: postgres:16
    container_name: short_url_db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Local123
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:


